In [ ]:
# 1. What is a Python library? Why ^o we use Python libraries?

# A Python library is a collection of modules and functions that provide pre-written, reusable code
# to perform common tasks. These libraries extend the capabilities of the Python programming language 
# and allow developers to save time by leveraging existing solutions instead of writing code from scratch.
# Libraries can cover a wide range of functionalities, from mathematical operations to web development, data manipulation,
# machine learning, and more.

In [ ]:
#2. What is the difference between Numpy array and List?

# NumPy arrays and Python lists are both used to store collections of items, but they have several differences.
# Here are some key distinctions:

# Type of Elements:

# NumPy Array: All elements in a NumPy array must be of the same data type. NumPy arrays are homogeneous.
# List: Lists can contain elements of different data types. Python lists are heterogeneous.

# Performance:

# NumPy Array: NumPy arrays are more efficient for numerical operations. They are implemented in C and optimized for performance.
# List: Lists are more flexible but may be less efficient for numerical operations due to their flexibility.

# Size:

# NumPy Array: NumPy arrays are more memory-efficient than lists. They use a contiguous block of memory for storage, 
# which reduces overhead.
# List: Lists have more overhead and are less memory-efficient compared to NumPy arrays.


# Functionality:

# NumPy Array: NumPy provides a wide range of mathematical operations that can be applied to entire arrays without using
# explicit loops. This is known as vectorization.
# List: Lists are more general-purpose and provide basic operations, but for complex mathematical operations, you often 
# need to use loops.


# Syntax:

# NumPy Array: NumPy provides a specialized array object (numpy.ndarray) with its own set of functions and methods.
# List: Lists are part of the Python core language and have a simpler syntax.


# Additional Features:

# NumPy Array: NumPy arrays come with advanced features such as broadcasting, slicing, and reshaping, making them powerful
# for numerical computing.
# List: Lists are more general-purpose and do not have specialized features for numerical operations.

In [11]:
# 3. Fin^ the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]


import numpy as np

lis = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

arr = np.array(lis)
print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 4)
12
2


In [18]:
# 4. Write python code to access the first row of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(arr[0,:])

[1 2 3 4]


In [20]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(arr[2,3])

12


In [30]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

odd_indexed_elements = arr[1::2,:]
odd_indexed_elements

array([[5, 6, 7, 8]])

In [43]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

import numpy as np

arr = np.random.randint(0,2,(3,3))
print(arr)

[[1 0 1]
 [0 0 0]
 [1 0 0]]


In [28]:
# 8. Describe the difference between np.random.rand and np.random.randn?

# np.random.rand:

# Functionality: Generates random numbers from a uniform distribution(When we say random numbers are uniformly distributed
#                 between 0 and 1, it means that each number in the range [0, 1) has an equal probability of being generated.) 
#                 over the interval [0, 1).
# Shape: Accepts dimensions as separate arguments (not as a tuple).
# Example:

print(np.random.rand(2, 3))  # Generates a 2x3 array of random numbers between
                                   
                                   
                                   
# np.random.randn:

# Functionality: Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
# Shape: Accepts dimensions as separate arguments (not as a tuple).
# Numbers generated from this distribution can take any real value, and they are more likely to be close to 0 (the mean)
# and less likely to be far from 0.
# Example:

print(np.random.randn(2, 3)) # Generates a 2x3 array of random numbers from a standard normal distribution

[[0.3800413  0.20462609 0.68349186]
 [0.21291378 0.72248446 0.62852843]]
[[ 1.07537641  0.19342699  0.91852199]
 [-0.59263899  1.41355526 -0.67030345]]


In [51]:
# 9. Write code to increase the dimension of the following array?
# [[1, 2, 3, 4],
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

arr = arr[:,:,np.newaxis]
print(arr)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [55]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(arr.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [70]:
# 11. Consider the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Perform the following operation using Python1
# 1) Index wise multiplication
# 2) Matix multiplication
# 3) Add both the matix
# 4) Subtact matix B from A
# 5) Divide Matix B by A


import numpy as np

A2 =  [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
B2 =  [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

A2 = np.array(A2)
B2 = np.array(B2)

product_index_wise = A2*B2
matrix_multiplication = np.matmul(A2,B2.T)
matrix_add = A2 + B2
difference = A2-B2
divide = B2 / A2


print(product_index_wise)
print()
print(matrix_multiplication)
print()
print(matrix_add)
print()
print(difference)
print()
print(divide)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
# 12. Which function in Numpy can be used to swap the byte order of an array?
import numpy as np

# Create an array with some data
arr = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order
arr_byteswapped = arr.byteswap()

print("Original array:", arr)
print("Byteswapped array:", arr_byteswapped)



Original array: [1 2 3 4]
Byteswapped array: [16777216 33554432 50331648 67108864]


In [49]:
# 13. What is the significance of the np.linalg.inv function?

# The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix. 
# In linear algebra, the inverse of a matrix is a matrix that, when multiplied with the original matrix, 
# gives the identity matrix.

import numpy as np

# Define a 2x2 matrix
A = np.array([[4, 7], [2, 6]])

# Calculate the inverse
A_inv = np.linalg.inv(A)

print("Original Matrix:")
print(A)

print("\nInverse Matrix:")
print(A_inv)

# Verify: A * A_inv should be the identity matrix
identity_matrix = np.dot(A, A_inv)
print("\nVerification (should be Identity Matrix):")
print(identity_matrix)


Original Matrix:
[[4 7]
 [2 6]]

Inverse Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]

Verification (should be Identity Matrix):
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [50]:
# 14. What does the np.reshape function do, and how is it used?

import numpy as np

# Create a 1D array with 12 elements
arr_1d = np.arange(12)
print("Original 1D Array:")
print(arr_1d)

# Reshape the 1D array into a 3x4 2D array
arr_2d = np.reshape(arr_1d, (3, 4))
print("\nReshaped 2D Array (3x4):")
print(arr_2d)

# Reshape the 1D array into a 2x6 2D array
arr_2d_2 = np.reshape(arr_1d, (2, 6))
print("\nReshaped 2D Array (2x6):")
print(arr_2d_2)

# Reshape the 1D array into a 3D array with shape (2, 2, 3)
arr_3d = np.reshape(arr_1d, (2, 2, 3))
print("\nReshaped 3D Array (2x2x3):")
print(arr_3d)


Original 1D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped 2D Array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped 2D Array (2x6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Reshaped 3D Array (2x2x3):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [52]:
# 15. What is broadcasting in Numpy?

# Broadcasting in NumPy is a mechanism that allows arrays of different shapes to be combined, or "broadcasted,"
# to perform arithmetic operations without explicitly reshaping the arrays. This makes it possible to perform 
# element-wise operations on arrays of different shapes and sizes.

import numpy as np

# 1D array
arr1 = np.array([1, 2, 3])

# Scalar
scalar = 2

# Broadcasting: Adding a scalar to a 1D array
result = arr1 + scalar

print("Original Array:")
print(arr1)

print("\nBroadcasted Result:")
print(result)


# In this example, the scalar value 2 is broadcasted to each element of the 1D array arr1. The result is [3, 4, 5].
# The scalar is effectively treated as a 1D array with a shape of (1,), and it gets broadcasted along the dimension
# of the array.

# Broadcasting simplifies the syntax of array operations and improves code readability. It allows for more concise
# and expressive code when working with arrays of different shapes. However, it's essential to understand the broadcasting
# rules to avoid unexpected behavior.

Original Array:
[1 2 3]

Broadcasted Result:
[3 4 5]
